# ### Specify the Docker image
image: mcr.microsoft.com/dotnet/sdk:6.0

build:
  stage: build
  # ### Build all projects discovered from solution file.
  
  script:
    - 'dotnet build RPGHeroes.sln'

tests:
  stage: test
  # ### Run the tests
  
  script:
    - 'dotnet test RPGHeroes.Tests/RPGHeroes.Tests.csproj'

